default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: elearning
  # password: learning@123

development:
  <<: *default
  database: elearning_development


test:
  <<: *default
  database: elearning_test
  password: learning@123
  host: localhost

production:
  <<: *default
  database: elearning_production
  username: elearning
  host: localhost
  password: learning@123
